---
title: "Advanced Statistical Methods"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
---


#### Outline

Big Data is a heated topic in a variety of fields such as biology and finance. The challenge of understanding these data has led to the development of new statistical tools and developed new areas such as machine learning and bioinformatics. Many of these tools are developed based on traditional statistical thinking, but are often expressed with different terminology.

In this project, students are expected to choose one or several topics and apply the methods to real datasets:
Logistic regression, classification and regression trees, neural networks, boosting, bagging, unsupervised learning, signal processing, random forests and data visualization, etc. Students are expected to demonstrate their understanding of the tools, apply the tools using software and interpret software’s the results.

#### Notes

  + Some Basic Plotting [Note](tt1.html)
  
  + Random forest [Note](randomforest.html)
  
  + Others
  
#### Past Students

  * 2022 - 2023
  
    + Zibo Yu: Application of support vector machine and its model in judging whether the charging stations of electric cars are faulty
    
    + YuZhe Xia: Using PCA and CNN in Cat Breeds Recognition
    
    + Ruofan Mao: Image Classification based on Underlying Feathers 
    
    + Zhuo Chen: Image Super-resolution Based on Convolutional Neural Network
    
    + Can He: Novel cluster-based machine learning approach of analyzing video games on the Steam platform
    
    + Siqi Wang: Data Reduction Methods and Clustering Algorithms in Case of World Happiness Index

  * 2021 - 2022
  
    + Zhiyi Wang [Clustering Methods and Its Application on Nutrition Facts of Mcdonald’s Breakfast Menu](1821891_Zhiyi Wang_2022.pdf)

    + Xinyi Yue [Unsupervised Learning Methods and its Applications on Customer Personality Analysis](1823376_Xinyi Yue_2022.pdf)

  * 2020 - 2021
    
    + Liangliang Zhu [Thesis](1718999_Liangliang Zhu_2021.pdf)
    
    + Rui Liu [Thesis](1718304_Rui Liu_2021.pdf)
    
    + Yeyu Wang [Thesis](1715617_Yeyu Wang_2021.pdf)
    
    
#### Interesting Reading

  * How the global health security index and environment factor influence the spread of COVID-19: A country level analysis [Link](https://www.sciencedirect.com/science/article/pii/S2352771421000252)