---
title: "Epidemiology"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
---

#### Outline

Coronavirus disease 2019 (COVID-19), an infectious disease caused by the infection of severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2), is spreading and causing the global coronavirus pandemic. The viral dynamics of SARS-CoV-2 infection have not been quantitatively investigated intensely.

In this project, students are expected to understand the viral dynamic modelling through ODE.
  
#### Past Stuents

  * 2021 - 2022
  
    + Xueke Zhang [Modelling of Covid-19 Transmission Dynamic in India](1824292_xueke zhang_2022.pdf)
    
    + Yipei Guo [Analyse the Spread of Covid-19 in United
States With an Epidemic Dynamic Model](1823319_Yipei Guo_2022.pdf)

#### Reference

  * Allen, L. J., Brauer, F., Van den Driessche, P., \& Wu, J. (2008). *Mathematical epidemiology* (Vol. 1945). Berlin: Springer.
  * Brauer, F., Driessche, P. D., & Wu, J. (2008). Lecture notes in mathematical epidemiology. Berlin, Germany. Springer, 75(1), 3-22.
  * Martcheva, M. (2015). *An introduction to mathematical epidemiology* (Vol. 61). New York: Springer.
  * Brauer, F. (2017). Mathematical epidemiology: Past, present, and future. *Infectious Disease Modelling*, 2(2), 113-127.
  * [Sample Website 1](http://sbfnk.github.io/mfiidd/introduction.html)
  * [Sample Website 2](https://bookdown.org/janengelstaedter/biol3360modelling3/continuous-time-models-in-several-variables.html)
  