---
title: "Survival Analysis"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
---

#### Outline

Survival data, where the primary outcome is time to a specific event, arise in many areas of biomedical research, including clinical trials and epidemiological studies. Many survival methods are extensions of techniques used in linear regression and categorical data, while other aspects of this field are unique to survival data.

In this project, students are expected to learn some survival analysis topics: Cox Model, AFT Model and Frailty Model, etc. Students are expected to demonstrate their understand of the model and interpret the results of application.

  
#### Past Students

  * 2021 - 2022
  
    + Zhaobing Fu [Reimplement Mixture Cure Models in Oncology With R](1824353_Fu Zhaobing_2022.pdf)

    + Wei Zhou [Estimation Methods for the Semiparametric Accelerated Failure Time Mixture Cure Model](1825310_Wei_Zhou_2022.pdf)

  * 2020 - 2021
    
    + Yue Ju [Thesis](1718235_Yue Ju_2021.pdf)
    

